### ISSUE TITLE
RimoChan的打招呼

### ISSUE THREAD

**Issue by RimoChan** [kagami-project/Kagami#108]
互加follow之後我的Librian在12小時內加了7星……你的影響力好大啊。
關於隔壁的Stella標記語言，我最近也在想怎麼把Librian的liber語言實際地分離出來。不知道Stella要實現什麼樣的功能？<sub>要不試試liber……</sub>

<sub>……突然不知道爲什麼開始害羞起來了，</sub>我什麼都沒說哦？

雖然只是就想打招呼，但是各種調查之後還是找不到你的聯絡方式結果要變成issue聊天大法了。

**Comment by RinGotou** [comment]
感谢关注！其实也是个透明人来着。。。。（
最近因为在忙于准备年底的研究生入学考试，所以这边暂时就没有开始编写工作留了个空仓库，大部分功能和设计什么的都还在构思阶段。。。。等到有空闲时间开始编写的时候我会试着参考一下设计。
联系方式的话因为目前SNS使用得不多，如果有Twitter的话可以直接在Twitter上直接找@RinGotou pm就行，我看到消息的话会尽快回复的。

**Comment by RimoChan** [comment]
啊，忘記講故事了……
今天下午我突然想到雖然是「後藤 鈴」但是寫成「RinGotou」就像是「りんご糖」，後來發現真的蘋果糖居然是「りんご飴」……

**Comment by RimoChan** [comment]
順便再講故事，之前看到你的狀態欄寫的「Undergraduate entrance examination」……
我想了想——「本科入學考試？競賽的高中生都這麼厲害的嗎？好像不對NOIP也沒有編譯原理啊？」
我突然明白了，你是蘿莉BBA！(劃掉)

正好我也在準備研究生入學考試……所以我們同年？
這個時候應該貼上表情「喂，老公我在<del>跑步</del>考研.jpg」

我一開始其實自己找到了你的twiter<sub>(沒錯我就是人力智能爬蟲RimoChan)</sub>，但是我自己關注的全是什麼福利姬女裝還有做色色的模型的人要是被你認出來的豈不是暴露Xp，然後就會被手腕高超的人找到我家，然後被綁起來這樣那樣……

**Comment by RinGotou** [comment]
直觉上这么一说还真的有点会想到苹果糖（
现在绝赞高等数学地狱中
噗，人设好像不太对劲发展到某些重口AVG上了。。。。。。

**Comment by RinGotou** [comment]
啊那个status其实是笔误，不知道什么时候写上去的了。。。（

**Comment by RimoChan** [comment]
正好這兩天還沒填志願，你打算去哪個學校？我因爲本科是985了，想去找一些性價比高的學校來考。

順便，關於高等数学，我前天在複習反向傳播的時候想到了一個精妙的求導公式，如果你是數學一的話應該用得上……

**Comment by RinGotou** [comment]
学校暂时不方便透露，不过我学校很烂就是了很多东西我是自己看的所以很不全面（没有开课）
因为issues版聊的话会影响到subscribe的人所以就不便多聊了
