### ISSUE TITLE
Compiling error on Linux machine

### ISSUE THREAD

**Issue by vgxbj** [kagami-project/Kagami#120]
刚刚玩了一下 `Kagami` 发现在我的机器无法编译成功，看了一下是因为项目中使用了 [`Microsoft Extension` ](https://docs.microsoft.com/en-us/cpp/standard-library/exception-class?view=vs-2019)

> The constructors exception(const char* const &message) and exception(const char* const &message, int) are Microsoft extensions to the C++ Standard Library.

把这行
https://github.com/kagami-project/Kagami/blob/f39c20266b3db40b9d651328a330219fa3f76691/src/machine.h#L263

暂时改成
```c++
std::exception(std::runtime_error(msg)) {}
```
可以编译成功

不太清楚这样改是否合理，所以开了这个 Issue.

**Comment by RinGotou** [comment]
这个改动合理, 我之前没有查阅标准文档踩了和以前使用basic_ifstream用了Microsoft extesnion一样的坑, 稍后就会在testing分支修复, thanks!

**Comment by RinGotou** [comment]
已经在 b8fb43e51e48ce35b2f5931b440ff87c33ed8838 上修复而且merge到master了, 你可以试试能否编译通过(手上暂时没有Linux设备可用)

**Comment by vgxbj** [comment]
嗯，可以通过编译了，不过好像 Parser 有些问题，BasicSample 里的 [`extension.kagami`](https://github.com/kagami-project/docs-and-samples/blob/master/BasicSample/extension.kagami) 好像是由于多行注释无法使用

最小的测试脚本
```kagami
=begin
This is multi-line comment
=end
```

```bash
☁  BasicSample [master] ⚡  kagami -script=comments.kagami && cat project-kagami.log 
[Sun Mar  1 14:09:18 2020](Line:3)Error:Invalid 'end' token at line 3
```

**Comment by RinGotou** [comment]
可能是在我以前修改parser的时候把这一部分的一些逻辑改坏了, 我尝试调一下(这部分代码太乱了, 调起来比较麻烦)

**Comment by vgxbj** [comment]
也许可以弄一个 CI :laughing:

**Comment by RinGotou** [comment]
好主意, 过段时间试一下(

**Comment by RinGotou** [comment]
"=end"识别错误的原因是不知道什么时候判断注释块的语句漏了一个"!"..............Orz
